version: '3.1'

services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Pwd1234!
      MYSQL_DATABASE: kube
      MYSQL_USER: username
      MYSQL_PASSWORD: Pwd1234!
