apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-pv
  labels:
    app: code-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "{NFS-server-IP}"
    path: "/var/code"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-pvc
  labels:
    app: code-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
