apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-config-pv
  labels:
    app: nginx-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "{NFS-server-IP}"
    path: "/var/config.d"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-config-pvc
  labels:
    app: nginx-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
